### ISSUE TITLE
player spawns inside planet

### ISSUE THREAD

**Issue by punto-** [punto-/solar_system_demo#12]
take a spaceship to a different planet (eg Mars), log out, log in with the same username. The player spawns inside the planet, and reference body is "Earth".

Server needs to know the current reference body, also client needs to make sure the player is not stuck inside the planet

**Comment by Facundo15** [comment]
To know if it is not inside the planet, it might be a good idea to add a collision cube in the center of each reference body, the player will constantly launch a beam towards that cube, if it detects it it is because it crossed the planet, but if not it means that has "floor" on it
