### ISSUE TITLE
Inventory not maintained for users in multiplayer server, also weird client bugs

### ISSUE THREAD

**Issue by punto-** [punto-/solar_system_demo#3]
Steps to repoduce:

- login with a user, eg "character_15"
- pick up some coal
- restart game and login with the same username

Observed issues always:

- player position is not maintained
- inventory is not maintained

Observed issues sometimes:

- player spawns twice (client can control only one)
- the sun spawns twice, lens flare is very aggresive
- when player tries to pick up a mineral, error "mineral already picked up" shows up, and needs to be clicked 3 times to dismiss

**Comment by Facundo15** [comment]
fixed
