### ISSUE TITLE
colisiones 

### ISSUE THREAD

**Issue by jessGia** [punto-/solar_system_demo#8]
lugares de problemas:

1. Las rocas grandes, se puede estar dentro de una sin que otros users te vean

<img width="962" alt="collision in big rock" src="https://github.com/Untitled-Planets/solar_system_demo/assets/22275069/f18c2b61-7d77-43b1-ba0d-2b95bc286181">

2. Dentro de la estructura del aro gigante en el tope de la plataforma
<img width="962" alt="collision 3" src="https://github.com/Untitled-Planets/solar_system_demo/assets/22275069/f45072dd-c429-425c-95b3-3d93bd80000b">

3. En la plataforma para subir al aro, al borde en la pared para no caer
<img width="962" alt="collision 2" src="https://github.com/Untitled-Planets/solar_system_demo/assets/22275069/2fa6073f-7299-43b0-92e9-c08825768d29">

4. En la cima de la plataforma de subida
<img width="962" alt="collision" src="https://github.com/Untitled-Planets/solar_system_demo/assets/22275069/899fab6d-9443-4fbb-b993-08c991100287">

5. Parte baja posterior de la rampa mirando hacia la maquina de carbon
![colision parte baja detras de la rampa mirando a la maquina de carbon](https://github.com/Untitled-Planets/solar_system_demo/assets/22275069/ccb17667-fcad-4460-9ae2-8c64cec0e2f1)

6. Del mismo lado que el anterior pero punto contrario de la pared mirando a la maquina de carbon en el brazo de la plataforma
![brazo](https://github.com/Untitled-Planets/solar_system_demo/assets/22275069/ace81dd9-426b-4fdb-adc7-3e388c240fdd)

**Comment by Facundo15** [comment]
A partir de la malla de cada uno genere su forma de colision exactam. Con excpecion de la roca grande, dado que al parecer es un placeholder y se toma la escena para fusionarlo con la malla del planeta, por algun motivo no toma la colision, y por ahora hasta que lo reviso las quite hasta que sepa porque y como se fusionan las rocas con el mundo
